#!/usr/bin/python
import sys
import time
import Adafruit_DHT
import httplib, urllib
import json
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(24,GPIO.IN,pull_up_down=GPIO.PUD_UP)
deviceId = "DaqpJ9pk"
deviceKey = "FtZyZYF7b0Ho8drT"
def post_to_mcs(payload):
        headers = {"Content-type": "application/json", "deviceKey": deviceKey}
        not_connected = 1
        while (not_connected):
                try:
                        conn = httplib.HTTPConnection("api.mediatek.com:80")
                        conn.connect()
                        not_connected = 0
except (httplib.HTTPException, socket.error) as ex:
                        print ("Error: %s" % ex)
                         # sleep 10 seconds
        conn.request("POST", "/mcs/v2/devices/" + deviceId + "/datapoints", jso$
        response = conn.getresponse()
        print( response.status, response.reason, json.dumps(payload), time.strf$
        data = response.read()
        conn.close()
sensor_args = { '11': Adafruit_DHT.DHT11,
                '22': Adafruit_DHT.DHT22,
                '2302': Adafruit_DHT.AM2302 }

while True:
        h0,t0=Adafruit_DHT.read_retry(sensor,pin)
        if h0 is not None and t0 is not None:
                print(' The current humidity is{1:0.1f}%'.format(h0))
                time.sleep(10)
        else:
                print('Failed to get reading. Try again!')
                sys.exit(1)
