#!/usr/bin/python
import sys
import time
import Adafruit_DHT
import httplib, urllib
import json
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(24,GPIO.IN,pull_up_down=GPIO.PUD_UP)
while True:
        SwitchStatus = GPIO.input(23)
        if(SwitchStatus == 1):
                        print('*** SWITCH ON ***')
                        time.sleep(0.5)
        else:
                        print('*** SWITCH OFF ***')
                        time.sleep(0.5)
